catalogs:
  build:
    "@wxt-dev/module-solid": 1.1.3
    ts-morph: 26.0.0
    typescript: 5.8.3
    typescript-eslint: 8.38.0
    wxt: 0.20.7
  frontend:
    solid-js: 1.9.7
  inlined:
    stats.js: 0.17.0
  lint:
    eslint: 9.31.0
    globals: 16.3.0
    prettier: 3.6.2
  prod:
    "@webext-core/messaging": 2.3.0
    camelcase-keys: 9.1.3
    snakecase-keys: 9.0.2
    stats.js: 0.17.0
    up-fetch: 2.1.8
    valibot: 1.1.0
  script:
    "@sinclair/typemap": 0.10.1
    tsx: 4.20.3
  types:
    "@types/stats.js": 0.17.4
    "@types/node": 24.1.0
