catalogs:
  build:
    "@wxt-dev/module-solid": 1.1.3
    ts-morph: 26.0.0
    typescript: 5.9.2
    typescript-eslint: 8.39.0
    wxt: 0.20.7
  frontend:
    solid-js: 1.9.8
  inlined:
    stats.js: 0.17.0
  lint:
    eslint: 9.32.0
    globals: 16.3.0
    prettier: 3.6.2
  prod:
    "@webext-core/messaging": 2.3.0
    es-toolkit: 1.39.8
    stats.js: 0.17.0
    up-fetch: 2.3.0
    valibot: 1.1.0
  script:
    "@sinclair/typemap": 0.10.1
    tsx: 4.20.3
  types:
    "@types/stats.js": 0.17.4
    "@types/node": 24.2.0
