catalogs:
  build:
    '@typescript/native-preview': 7.0.0-dev.20250927.1
    '@wxt-dev/module-solid': 1.1.4
    ts-morph: 27.0.2
    typescript: 5.9.3
    typescript-eslint: 8.46.2
    wxt: 0.20.11
  frontend:
    solid-js: 1.9.10
  inlined:
    stats.js: 0.17.0
  lint:
    eslint: 9.38.0
    globals: 16.4.0
    prettier: 3.6.2
  prod:
    '@webext-core/messaging': 2.3.0
    es-toolkit: 1.41.0
    stats.js: 0.17.0
    up-fetch: 2.5.0
    valibot: 1.1.0
  script:
    '@sinclair/typemap': 0.10.1
    tsx: 4.20.6
  types:
    '@types/node': 24.9.1
    '@types/stats.js': 0.17.4
