catalogs:
  build:
    '@typescript/native-preview': 7.0.0-dev.20260603.1
    '@wxt-dev/module-solid': 1.1.4
    ts-morph: 28.0.0
    typescript: 6.0.3
    typescript-eslint: 8.60.1
    wxt: 0.20.26
  frontend:
    solid-js: 1.9.13
  inlined:
    stats.js: 0.17.0
  lint:
    eslint: 10.4.1
    globals: 17.6.0
    prettier: 3.8.3
  prod:
    '@webext-core/messaging': 3.0.2
    es-toolkit: 1.47.0
    stats.js: 0.17.0
    up-fetch: 2.6.0
    valibot: 1.4.1
  script:
    '@sinclair/typemap': 0.10.1
    tsx: 4.22.4
  types:
    '@types/node': 25.9.1
    '@types/stats.js': 0.17.4
