catalogs:
  build:
    '@wxt-dev/module-solid': 1.1.4
    ts-morph: 27.0.0
    typescript: 5.9.2
    typescript-eslint: 8.43.0
    wxt: 0.20.11
  frontend:
    solid-js: 1.9.9
  inlined:
    stats.js: 0.17.0
  lint:
    eslint: 9.35.0
    globals: 16.4.0
    prettier: 3.6.2
  prod:
    '@webext-core/messaging': 2.3.0
    es-toolkit: 1.39.10
    stats.js: 0.17.0
    up-fetch: 2.4.0
    valibot: 1.1.0
  script:
    '@sinclair/typemap': 0.10.1
    tsx: 4.20.5
  types:
    '@types/node': 24.3.3
    '@types/stats.js': 0.17.4
