// Typelizer digest 461b03f9358f0c11d885e2b3687ea2c3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaShow = {
  status: "success" | "error";
  airing_status: "upcoming" | "ongoing" | "completed";
  country: string;
  description: string | null;
  id: number;
  last_watched_episode: number;
  name: string;
  total_episodes: number;
  watch_status: "not_started" | "watching" | "finished";
  metadata: object;
}

export default DramaShow;
