// Typelizer digest f229fb27cbb361bc313b41c1dc72b337
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaIndex = {
  id: number;
  last_watched_episode: number;
  name: string;
  watch_status: "not_started" | "watching" | "finished";
  metadata: object;
}

export default DramaIndex;
