// Typelizer digest 2bc4815df24df5c366dff35195544d31
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaIndex = {
  id: number;
  last_watched_episode: number;
  name: string;
  watch_status: "not_started" | "watching" | "finished";
}

export default DramaIndex;
