// Typelizer digest 41a2d2fc81fb14c0bd1ca0eb6cecfe99
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaShow = {
  status: "success" | "error";
  airing_status: "upcoming" | "ongoing" | "completed";
  country: string;
  description: string | null;
  id: number;
  last_watched_episode: number;
  name: string;
  total_episodes: number;
  watch_status: "not_started" | "watching" | "finished";
  metadata: object;
  poster_url: string | null;
}

export default DramaShow;
