// Typelizer digest ef42f1fc49c3b6ed8c750587a5b987f9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaShow = {
  status: "success" | "error";
  airing_status: "upcoming" | "ongoing" | "completed";
  country: string;
  description: string | null;
  id: number;
  last_watched_episode: number;
  name: string;
  total_episodes: number;
  watch_status: "not_started" | "watching" | "finished";
}

export default DramaShow;
