// Typelizer digest 199d2769976cbce3c08558c942026323
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DramaIndex = {
  id: number;
  last_watched_episode: number;
  name: string;
  watch_status: "not_started" | "watching" | "finished";
  metadata: object | null;
  poster_url: string | null;
}

export default DramaIndex;
