// Typelizer digest d66e2f73e8068da6471bbe48d2ae2b2f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Error = {
  status: "success" | "error";
  message: string;
}

export default Error;
