// Typelizer digest cf3c91d0327c2b70656b0acc908d3853
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Success = {
  status: "success" | "error";
  message: string;
}

export default Success;
